---
- hosts: "{{ cli_host }}"

  pre_tasks:
    - name: Get pre-epoch time
      become: false
      shell: "TZ=':US/Eastern' date +%s"
      register: epoch
      changed_when: false
      check_mode: no

    - name: Send initial Slack notification
      become: false
      local_action:
        module: slack
        token: "{{ slack_token }}"
        channel: "{{ slack_channel | default('#operations') }}"
        attachments:
        - text: "Deploying {{ cli_host }}"
          title: "Host: {{ ansible_hostname }}"
          color: "#d3d3d3"
      when: slack_token is defined
      ignore_errors: yes

  vars_files:
    - vars/{{ cli_host }}.yml

  roles:
    - ../ansible-role-notifyssh
    - ./roles/base
    - pgporada.mongodb
    - pgporada.unifi
    - ./roles/certbot-digitalocean
    - geerlingguy.certbot
    - ./roles/nginx-dhparams
    - geerlingguy.nginx

  post_tasks:
    - name: Get post-epoch time
      become: false
      shell: "TZ=':US/Eastern' date +%s"
      register: epoch
      changed_when: false
      check_mode: no

    - name: Send failure Slack notification
      become: false
      local_action:
        module: slack
        token: "{{ slack_token }}"
        channel: "{{ slack_channel | default('#operations') }}"
        attachments:
        - text: "Failed task: {{ ansible_failed_task }}, failed result: {{ ansible_failed_result }}"
          title: "Host: {{ ansible_hostname }}"
          color: danger
      when: slack_token is defined and ansible_failed_task is defined
      ignore_errors: yes

    - name: Send passing Slack notification
      become: false
      local_action:
        module: slack
        token: "{{ slack_token }}"
        channel: "{{ slack_channel | default('#operations') }}"
        attachments:
        - text: "Successfully deployed {{ cli_host }}"
          title: "Host: {{ ansible_hostname }}"
          color: good
      when: slack_token is defined and ansible_failed_task is undefined
      ignore_errors: yes
...
