---
- hosts: "{{ cli_host }}"
  vars_files:
    - vars/{{ cli_host }}.yml
  roles:
    - ./roles/base
    - pgporada.mongodb
    - pgporada.unifi
    - ./roles/certbot-digitalocean
    - geerlingguy.certbot
    - ./roles/nginx-dhparams
    - geerlingguy.nginx
...
